### ISSUE TITLE
color blindness in women

### ISSUE THREAD

**Issue by r2evans** [wilkelab/SDS375#1]
Good afternoon, Professor!

I frequently see your tweets and posts and enjoy the perspectives and advice you give. I recently saw a mention to *color spaces and color-vision deficiency*, and on slide 23 it says `5%–8% of men are color blind!`

I suspect that an in-class lecture (or speaker's notes) on this topic would highlight the increased likelihood of males over females (https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/color-blindness/causes-color-blindness, I wanted to learn :-). I wonder, though, that uninformed readers might see that text and wonder if the slide cares more about addressing men's colorblindness than women's.

There is no accusation in this, just a glancing reaction (and a superficial one at that). I appreciate this content specifically and your efforts in this and other R-based tools in general. Thanks!

**Comment by clauswilke** [comment]
This is discussed in the textbook I link to:
https://clauswilke.com/dataviz/color-pitfalls.html#not-designing-for-color-vision-deficiency
